export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILED = 'USER_DETAILS_FAILED';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED';

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED';
export const USER_EDIT_RESET = 'USER_EDIT_RESET';


export const USER_GENERATE_TOKEN_REQUEST = 'USER_GENERATE_TOKEN_REQUEST';
export const USER_GENERATE_TOKEN_SUCCESS = 'USER_GENERATE_TOKEN_SUCCESS';
export const USER_GENERATE_TOKEN_FAILED = 'USER_GENERATE_TOKEN_FAILED';

export const USER_GET_TOKEN_REQUEST = 'USER_GET_TOKEN_REQUEST';
export const USER_GET_TOKEN_SUCCESS = 'USER_GET_TOKEN_SUCCESS';
export const USER_GET_TOKEN_FAILED = 'USER_GET_TOKEN_FAILED';

export const USER_RECHARGE_REQUEST = 'USER_RECHARGE_REQUEST';
export const USER_RECHARGE_SUCCESS = 'USER_RECHARGE_SUCCESS';
export const USER_RECHARGE_FAILED = 'USER_RECHARGE_FAILED';

export const USER_PAYMENT_REQUEST = 'USER_PAYMENT_REQUEST';
export const USER_PAYMENT_SUCCESS = 'USER_PAYMENT_SUCCESS';
export const USER_PAYMENT_FAILED = 'USER_PAYMENT_FAILED';